Numpy for Python

In [1]:
import numpy as np
a=[9,3,3,5]
print(np.array(a))

[9 3 3 5]


In [2]:
l=[1,2,3,4,5]
a=np.array(l)
print("Simple Numpy Array:",a)

Simple Numpy Array: [1 2 3 4 5]


In [2]:
import numpy as np
a0=np.zeros((3,3))
a1=np.ones((3,3))
af=np.full((2,2),67)
ar=np.arange(0,10,2)
la=np.linspace(0,1,5)
print("Zero Array:","\n",a0)
print("Ones Array:","\n",a1)
print("Constant Array:",",",af)
print("Range Array:","\n",ar)
print("linspace Array:",",",la)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: , [[67 67]
 [67 67]]
Range Array: 
 [0 2 4 6 8]
linspace Array: , [0.   0.25 0.5  0.75 1.  ]


np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [6]:
aq=np.random.rand(2,3)
an=np.random.randn(2,2)
ap=np.random.randint(1,10,size=(2,3))
aq
an
ap

array([[3, 3, 2],
       [9, 4, 1]])

np.eye(): Creates an identity matrix of specified size.

np.diag(): Constructs a diagonal array.

np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.

np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [8]:
im=np.eye(3)
da=np.diag([1,2,3])
ja=np.zeros_like(da)
n=np.ones_like(da)
print(im)
print(da)
print(ja)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


1.Accessing the elements in 1D Arrays

2.Accessing elements in multidimensional arrays

3.Slicing Arrays

4.Boolean indexing

5.Fancy Indexing



In [21]:
arr=np.array([10,20,30,40,50])
print("Accessing the element in 1d:",arr[0])

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Accessing the element in multiD:",matrix[1,2])

cube=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
#matrix[depth,row,column]
print("Accessing the element in multiD:",cube[1,2,0])

#start:stop:step
print(arr[1:4])
print(matrix[0:2,1:3])
#allows us to filter elements from 
# an array based on a condition and returns only those that meet it
print(arr[arr>20])
arr=np.array([10,15,20,25,30])
print(arr[(arr>10)&(arr<30)])
#Advancing INdexing
index=[0,2,4]
print(arr[index])


Accessing the element in 1d: 10
Accessing the element in multiD: 6
Accessing the element in multiD: 16
[20 30 40]
[[2 3]
 [5 6]]
[30 40 50]
[15 20 25]
[10 20 30]


6.Integer Array Indexing

7.Ellipsis() in indexing

8.using np.newaxis to add new dimensions

9.modifying array elements

In [27]:
#similar to fancy indexing and uses an array of integers 
# to select multiple elements from another array
arr=np.array([1,2,3,4,5])
print(arr[[0,2,4]])
# ellipis can be used to select all dimensions which are not 
# explicitly mentioned
cube=np.random.rand(4,4,4)
print(cube[...,0])
# np.newaxis to add new dimensions
print(arr[:,np.newaxis])
arr[1:3]=67
print(arr)

[1 3 5]
[[0.92805918 0.2665143  0.99634836 0.96429   ]
 [0.24741351 0.2413078  0.20294201 0.4266858 ]
 [0.14812822 0.34394442 0.82913004 0.20297906]
 [0.85714228 0.5220392  0.53044952 0.66661787]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[ 1 67 67  4  5]


how to access different rows of a multidimensional numpy array

In [28]:
arr=np.array([[10,20,30],[40,5,66],[70,88,94]])
print("Array:",arr)
res=arr[[0,2]]
print("Accessed Rows:",res)

Array: [[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed Rows: [[10 20 30]
 [70 88 94]]


In [29]:
arr=np.array([[101,20,3,10],[40,5,66,7],[70,88,9,141]])
print("Array:",arr)
res=arr[1]
print("Accessed Row:",res)

Array: [[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]
Accessed Row: [40  5 66  7]


In [ ]:
# 2D arrays
arr=np.array([[12,15,18],[25,30,35],[40,45,50]])
print("Array:",arr)
res1=arr[:2,:2]#first 2 rows first 2 columns
print("Accessed Elements:",res1)
res2=arr[1:,2:]
print("Accessed:",res2)

Array: [[12 15 18]
 [25 30 35]
 [40 45 50]]
Accessed Elements: [[12 15]
 [25 30]]
Accessed: [[35]
 [50]]


In [39]:
#3D arrays
arr=np.array([[[10,25,70],[30,45,55],[20,45,7]],[[50,65,8],[70,85,10],[11,22,33]]])
print("Array:",arr)
res=arr[:,[2]]
print("Accessed Elements:",res)

Array: [[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]
Accessed Elements: [[[20 45  7]]

 [[11 22 33]]]


In [40]:
import numpy as np

arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], 
                 [[50, 65, 8], [70, 85, 10], [11, 22, 33]],
                 [[19, 69, 36], [1, 5, 24], [4, 20, 96]]])
print("Array:")
print(arr)

res = arr[:,[0, 2]]
print("Accessed Rows:")
print(res)

Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20 96]]]
Accessed Rows:
[[[10 25 70]
  [20 45  7]]

 [[50 65  8]
  [11 22 33]]

 [[19 69 36]
  [ 4 20 96]]]


In [41]:
import numpy as np

arr = np.array([
    [[5, 10, 15], [20, 25, 30], [35, 40, 45]],
    [[2,  4,  6], [ 8, 10, 12], [14, 16, 18]],
    [[7, 14, 21], [28, 35, 42], [49, 56, 63]]
])
print("Array:")
print(arr)

res = arr[:, :2, :2]   # first 2 rows and first 2 columns from each 2D slice
print("Accessed Elements:")
print(res)

Array:
[[[ 5 10 15]
  [20 25 30]
  [35 40 45]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 7 14 21]
  [28 35 42]
  [49 56 63]]]
Accessed Elements:
[[[ 5 10]
  [20 25]]

 [[ 2  4]
  [ 8 10]]

 [[ 7 14]
  [28 35]]]


Reshape Numpy Array-python

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
r=a.reshape(2,3)
print(r)
a=np.array([1,2,3,4,5,6,7,8])
r=a.reshape(2,2,2)# into 2 blocks, 2x2 matrix
print(r)
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r=a.reshape(3,-1)# tells to create 3 rows and it computes the remaining 
#dimensions as 4columns,since 12%3=4
print(r)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Resizing the Arrays

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2,3))
print(arr)
arr.resize((3,4))
print(arr)
arr.resize((2,2))
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]
[[1 2]
 [3 4]]


Stacking:function to join multiple arrays by creating a new axis in the output array

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
res=np.stack((a,b),axis=0)#a and b become rows
print(res)
print(np.stack((a,b),axis=1))#a and b become columns 
print(np.stack((a,b),axis=-1))#same as axis 1 because it refers to the last dimension

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
x=np.array([[1,2,3],
           [4,5,6]])
y=np.array([[7,8,9],
           [10,11,12]])
print(np.stack((x,y),axis=0))#stacks arrays as two layers of a 3D arrays
print(np.stack((x,y),axis=1))#stacks row-wise
print(np.stack((x,y),axis=2))#stacks col-wise forming 3D structure 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
import numpy as np

m = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

n = np.array([[[10, 20], [30, 40]],
              [[50, 60], [70, 80]]])

print(np.stack((m, n), axis=0))#stacks arrays as 2 arrays
print(np.stack((m, n), axis=1))#stacks "planes" together
print(np.stack((m, n), axis=2))#stacks each corrosponding row
print(np.stack((m, n), axis=3))#stacks each corrosponding element as a new last axis

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


Splitting Arrays 

In [13]:
# Axis: The direction along which the array is split (0 for rows, 1 for columns).
# Sub-arrays: Smaller arrays created after splitting the original array.
# Splitting Methods: Functions like np.split(), np.hsplit(), np.vsplit() and np.array_split().
# Equal vs. Unequal Splits: Splits can divide data evenly, or slightly unevenly if needed (using array_split()).
arr=np.array([1,2,3,4,5,6])
res=np.array_split(arr,3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
import numpy as np
#vertical splitting
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
res = np.vsplit(arr, 2)
print(res)
#horizontal splitting 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
res = np.hsplit(arr, 2)
print(res)
#dsplit() is used for 3D arrays it splits the array along the third axis(axis=2)
arr=np.arange(24).reshape((2,3,4))
res=np.dsplit(arr,2)
print(res)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


Boardcasting:allows us to perform arithmetric operations on arrays of different shapes without reshaping them

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a + x)
# Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
# Dimension Padding: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
# Shape Compatibility: Two dimensions are compatible if they are equal or one of them is 1

[[11 12 13]
 [14 15 16]]


In [ ]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)
# Then it adds elements position-wise: [1, 3, 5] + [2, 4, 6] = [3, 7, 11] and [7, 9, 11] + [2, 4, 6] = [9, 13, 17]

[[ 3  7 11]
 [ 9 13 17]]


Arithemetric operations

In [2]:
import numpy as np
a=np.array([5,72,13,100])
b=np.array([2,5,10,30])
res=np.add(a,b)
res1=np.subtract(a,b)
res2=np.multiply(a,b)
res3=np.divide(a,b)
res4=np.power(a,b)
res5=np.mod(a,b)

In [3]:
print(res)
print(res1)
print(res2)
print(res3)
print(res4)
print(res5)

[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[        25 1934917632  419538377          0]
[ 1  2  3 10]


Aggregation Functions
(sum,mean,max,min)

In [ ]:
# sum
arr=np.array([5,10,15])
print(np.sum(arr))
arr=np.array([5,10,15,0.2])
print(np.sum(arr,dtype=np.uint8))#8-bit unsigned integer
print(np.sum(arr,dtype=np.float32))#floating-point arithemetric
# syntax:numpy.sum(arr,axis=None,dtype=None,out=None,initial=0,keepdima=False)
# arr: Input array whose elements are to be summed.
# axis: Axis along which the sum is computed. 0 -> column-wise, 1 -> row-wise and None -> entire array
# dtype: Data type of the returned sum.
# out: Output array to store the result.
# initial: Starting value of the sum.
# keepdims: Keeps the reduced axis as dimension in result

30
30
30.2


In [6]:
arr=np.array([[14,17,12,33,44],
              [15,6,27,8,19],
              [23,2,54,1,4]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=1,keepdims=True))

279
[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


In [ ]:
#mean
#numpy.mean(arr,axis=None,dtype=None,out=None)
arr=[20,2,7,1,34]
res=np.mean(arr)
print(res)
arr=[[14,17,12],
     [15,6,27],
     [23,2,54]]
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))
print(np.mean(arr))
arr=[[5,10,15],
     [3,6,9],
     [8,16,24]]
res=np.zeros(3)
np.mean(arr,axis=1,out=res)#OUT=RES  stores the row-wise mean values into res
print(res)

12.8
[17.33333333  8.33333333 31.        ]
[14.33333333 16.         26.33333333]
18.88888888888889
[10.  6. 16.]


In [ ]:
# numpy.maximum(arr1, arr2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None)

# Parameters:
# arr1: First input array (or scalar).
# arr2: Second input array (or scalar).
# out (optional): Array to store the result.
# where: Boolean mask; True positions are computed.
# dtype (optional): Data type of the output.
# casting / order: Controls data casting and memory layout (rarely used).

In [ ]:
# numpy.minimum(arr1, arr2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None)

# Parameters:
# arr1: First input array (or scalar).
# arr2: Second input array (or scalar).
# out: Optional array to store output.
# where: Boolean mask; only True positions are computed.
# dtype (optional): Data type of output.
# casting / order: Controls casting and memory layout (advanced use).

<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: "Roboto", sans-serif;
      background-color: #f0f7ff;
    }
    table {
      width: 75%;
      margin: 30px auto;
      border-collapse: collapse;
      background-color: white;
    }
    th {
      background-color: #1976d2;
      color: white;
      padding: 14px;
    }
    td {
      padding: 12px;
      border-bottom: 1px solid #ccc;
    }
    tr:hover {
      background-color: #e3f2fd;
    }
    td:first-child {
      font-weight: 600;
      color: #1565c0;
    }
  </style>
</head>
<body>

<table>
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>np.sin, np.cos, np.tan</td>
    <td>Compute sine, cosine, and tangent</td>
  </tr>
  <tr>
    <td>np.arcsin, np.arccos, np.arctan</td>
    <td>Compute inverse trigonometric functions</td>
  </tr>
  <tr>
    <td>np.sinh, np.cosh, np.tanh</td>
    <td>Compute hyperbolic functions</td>
  </tr>
  <tr>
    <td>np.deg2rad</td>
    <td>Convert degrees to radians</td>
  </tr>
  <tr>
    <td>np.rad2deg</td>
    <td>Convert radians to degrees</td>
  </tr>
  <tr>
    <td>np.hypot</td>
    <td>Compute hypotenuse of right triangle</td>
  </tr>
</table>

</body>
</html>


<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: "Inter", sans-serif;
      background-color: #fefefe;
    }
    table {
      width: 75%;
      margin: 30px auto;
      border-collapse: collapse;
      background-color: #ffffff;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    th {
      background-color: #4caf50;
      color: white;
      padding: 14px;
    }
    td {
      padding: 12px;
      border-bottom: 1px solid #ddd;
    }
    tr:hover {
      background-color: #e8f5e9;
    }
    td:first-child {
      font-weight: bold;
      color: #2e7d32;
    }
  </style>
</head>
<body>

<table>
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>np.amin, np.amax</td>
    <td>Minimum or maximum of array</td>
  </tr>
  <tr>
    <td>np.ptp</td>
    <td>Range (max − min) of array values</td>
  </tr>
  <tr>
    <td>np.percentile(a, p)</td>
    <td>p-th percentile of array values</td>
  </tr>
  <tr>
    <td>np.mean</td>
    <td>Compute mean of data</td>
  </tr>
  <tr>
    <td>np.median</td>
    <td>Compute median of data</td>
  </tr>
  <tr>
    <td>np.std</td>
    <td>Compute standard deviation</td>
  </tr>
  <tr>
    <td>np.var</td>
    <td>Compute variance</td>
  </tr>
  <tr>
    <td>np.average</td>
    <td>Compute average value</td>
  </tr>
</table>

</body>
</html>


<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: "Segoe UI", sans-serif;
      background-color: #fafafa;
    }
    table {
      width: 65%;
      margin: 30px auto;
      border-collapse: collapse;
      background-color: white;
      border: 1px solid #ccc;
    }
    th {
      background-color: #ff5722;
      color: white;
      padding: 12px;
    }
    td {
      padding: 10px;
      border-bottom: 1px solid #ddd;
    }
    tr:hover {
      background-color: #ffe0b2;
    }
    td:first-child {
      font-weight: bold;
      color: #e64a19;
    }
  </style>
</head>
<body>

<table>
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>np.bitwise_and</td>
    <td>Element-wise AND operation</td>
  </tr>
  <tr>
    <td>np.bitwise_or</td>
    <td>Element-wise OR operation</td>
  </tr>
  <tr>
    <td>np.bitwise_xor</td>
    <td>Element-wise XOR operation</td>
  </tr>
  <tr>
    <td>np.invert</td>
    <td>Bitwise NOT (invert) of elements</td>
  </tr>
  <tr>
    <td>np.left_shift</td>
    <td>Shift bits of elements to the left</td>
  </tr>
  <tr>
    <td>np.right_shift</td>
    <td>Shift bits of elements to the right</td>
  </tr>
</table>

</body>
</html>


In [10]:
import numpy as np

even = np.array([0, 2, 4, 6, 8, 16, 32])
odd  = np.array([1, 3, 5, 7, 9, 17, 33])

# Bitwise AND, OR, XOR
print("AND:", np.bitwise_and(even, odd))
print("OR :", np.bitwise_or(even, odd))
print("XOR:", np.bitwise_xor(even, odd))

# Bitwise NOT
print("Invert:", np.invert(even))

# Bit shifts
print("Left shift :", np.left_shift(even, 1))
print("Right shift:", np.right_shift(even, 1))

AND: [ 0  2  4  6  8 16 32]
OR : [ 1  3  5  7  9 17 33]
XOR: [1 1 1 1 1 1 1]
Invert: [ -1  -3  -5  -7  -9 -17 -33]
Left shift : [ 0  4  8 12 16 32 64]
Right shift: [ 0  1  2  3  4  8 16]


<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: "Poppins", sans-serif;
      background-color: #f4f6f8;
    }
    table {
      border-collapse: collapse;
      width: 70%;
      margin: 30px auto;
      background-color: #ffffff;
      box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    }
    th, td {
      padding: 14px;
      text-align: left;
      border-bottom: 1px solid #e0e0e0;
    }
    th {
      background-color: #3f51b5;
      color: white;
      letter-spacing: 0.5px;
    }
    tr:hover {
      background-color: #f1f3ff;
    }
    td:first-child {
      font-weight: 600;
      color: #3f51b5;
    }
  </style>
</head>
<body>

<table>
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>rint()</td>
    <td>Round to nearest integer towards zero.</td>
  </tr>
  <tr>
    <td>fix()</td>
    <td>Round to nearest integer towards zero.</td>
  </tr>
  <tr>
    <td>floor()</td>
    <td>Return the floor of the input, element-wise.</td>
  </tr>
  <tr>
    <td>ceil()</td>
    <td>Return the ceiling of the input, element-wise.</td>
  </tr>
  <tr>
    <td>trunc()</td>
    <td>Return the truncated value of the input, element-wise.</td>
  </tr>
</table>

</body>
</html>


<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: "Montserrat", sans-serif;
      background-color: #eef2f3;
    }
    table {
      width: 75%;
      margin: 30px auto;
      border-collapse: collapse;
      background-color: #ffffff;
      border-radius: 8px;
      overflow: hidden;
    }
    th {
      background-color: #009688;
      color: white;
      padding: 14px;
    }
    td {
      padding: 12px;
      border-bottom: 1px solid #ddd;
    }
    tr:hover {
      background-color: #e0f2f1;
    }
    td:first-child {
      color: #00796b;
      font-weight: bold;
    }
  </style>
</head>
<body>

<table>
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>np.exp()</td>
    <td>Compute e^x element-wise.</td>
  </tr>
  <tr>
    <td>expm1()</td>
    <td>Calculate exp(x) − 1 for all elements.</td>
  </tr>
  <tr>
    <td>exp2()</td>
    <td>Calculate 2^p for all p in the input array.</td>
  </tr>
  <tr>
    <td>log10()</td>
    <td>Return base-10 logarithm element-wise.</td>
  </tr>
  <tr>
    <td>log2()</td>
    <td>Return base-2 logarithm of x.</td>
  </tr>
  <tr>
    <td>log1p()</td>
    <td>Return natural log of (1 + x).</td>
  </tr>
  <tr>
    <td>logaddexp()</td>
    <td>Logarithm of the sum of exponentials.</td>
  </tr>
  <tr>
    <td>logaddexp2()</td>
    <td>Logarithm of sum of exponentials (base 2).</td>
  </tr>
</table>

</body>
</html>


In [11]:
import numpy as geek 
 
print("Is Real : ", geek.isreal([1+1j, 0j]))
print("Is Real : ", geek.isreal([1, 0]))

Is Real :  [False  True]
Is Real :  [ True  True]


In [12]:
import numpy as np
 
c1 = 2+4j
o1 = np.conj(c1)
print ("Output conjugated complex number of  2+4j : ", o1)
 
c2 =5-8j
o2 = np.conj(c2)
print ("Output conjugated complex number of 5-8j: ", o2)

Output conjugated complex number of  2+4j :  (2-4j)
Output conjugated complex number of 5-8j:  (5+8j)


In [13]:
import numpy as np
arr = [1, 2, 3, 4, 5, 6, 7, 8]
print(np.clip(arr, 2, 6))

[2 2 3 4 5 6 6 6]


<span style="font-family:Courier New">Matrix manipulation in Python</span>

<span style="font-family:Times New Roman">Matrix Operations in NumPy</span>


In [16]:
#element-wise
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[9,10]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))
print(np.multiply(x,y))
print(np.dot(x,y))

[[ 8 10]
 [13 15]]
[[-6 -6]
 [-5 -5]]
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
[[ 7 16]
 [36 50]]
[[25 28]
 [73 82]]


In [17]:
print(np.sum(y,axis=0))
print(np.sum(y,axis=1))
print(x.T)
print(y.T)

[16 18]
[15 19]
[[1 4]
 [2 5]]
[[ 7  9]
 [ 8 10]]


In [ ]:
a=[[1,2],[4,5]]
b=[[7,8],[9,10]]
rows=len(a)
# print(rows)=2
cols=len(a[0])
# print(cols)=2
c=[[0 for i in range(cols)] for j in range(rows)]
#ex:rows=2,cols=3
# C = [
#   [0, 0, 0],
#   [0, 0, 0]
# ]


2
2


Cij=Aij​+Bij
	​


In [21]:
for i in range(rows):
    for j in range(cols):
        c[i][j] = a[i][j] + b[i][j]
print("Addition:\n", c)

Addition:
 [[8, 10], [13, 15]]


In [23]:
D = [[0 for i in range(cols)] for j in range(rows)]
for i in range(rows):
    for j in range(cols):
        D[i][j] = a[i][j] - b[i][j]
print("Subtraction:\n", D)

E = [[0 for i in range(cols)] for j in range(rows)]
for i in range(rows):
    for j in range(cols):
        E[i][j] = a[i][j] / b[i][j]
print("Division:\n", E)

Subtraction:
 [[-6, -6], [-5, -5]]
Division:
 [[0.14285714285714285, 0.25], [0.4444444444444444, 0.5]]


<span style="font-family:Courier New">Products of vectors and matrics in Numpy</span>

In [25]:
# numpy.inner(arr1,arr2)
# inner product =dot product
a=np.array([2,6])
b=np.array([3,10])
print(np.inner(a,b))
# numpy.cross(arr1,arr2)
import numpy as np

# Define vectors as 3D (z=0 for 2D compatibility)
a = np.array([3, 6, 0])
b = np.array([9, 10, 0])

print("Cross product of vectors a and b =")
print(np.cross(a, b))

# Define matrices (already 3D rows)
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])

print("Cross product of matrices x and y =")
print(np.cross(x, y))


66
Cross product of vectors a and b =
[  0   0 -24]
Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]
